apiVersion: v1
kind: Pod
metadata:
  name: pdfmagic
  labels:
    app: pdfmagic
spec:
  containers:
  - name: pdfmagic
    image: minijacksparrow/pdfmagic
    resources:
      requests:
        cpu: 0.5
    ports:
    - containerPort: 8080
